Seccion 1
SebastianVelasquez2509/Swipe pull request #1
Opened 2023-07-14 19:22 UTC by SebastianVelasquez2509

2023-07-17 19:18 UTC, DanielCalleCO requested changes

2023-07-17 19:18 UTC, DanielCalleCO commented on Style.css
En que momento empiezas con los media query de movile first?

2023-07-24 14:17 UTC, DanielCalleCO requested changes
Sebas, no se ve bien ese fondo detrás de los iconos, dale un max-width

![image](https://github.com/SebastianVelasquez2509/Swipe/assets/100431019/49ec8460-c23d-4c46-b9b6-0d2c54589db3)

2023-07-24 15:06 UTC, SebastianVelasquez2509 commented
Hola Dani

2023-07-24 15:06 UTC, SebastianVelasquez2509 commented
Ya lo corrijo

2023-07-24 20:00 UTC, DanielCalleCO approved these changes

2023-07-24 20:01 UTC, merged